first stab to recover dump_dynamical_matrices in public branch
tdep-developers/tdep pull request #49
Opened 2024-03-21 16:36 UTC by mjv500

grabbed handy tool from old develop branches. Moved to src, and incorporated in build_things

2024-04-02 10:05 UTC, flokno requested changes
As I understand, the code currently reads in the force constants and dumps to an Abinit DDB file. Would `convert_forceconstant_to_abinit_ddb` be a better name, in line with https://github.com/ollehellman/tdep-devel/tree/master/src/convert_abinit_ddb_to_forceconstant ? 

Since this is a feature exclusive for Abinit, I'm thinking if it would be better to move this to a `utilities` folder that is optionally compiled.

Some comments are given in line

2024-04-02 22:18 UTC, mjv500 commented on tests/dump_dynamical_matrices/test_dump_dynamical_matrices.py
what are you running beyond "make"?

2024-04-02 22:18 UTC, mjv500 commented on src/dump_dynamical_matrices/ddb_io_out.F90
removed

2024-04-02 22:18 UTC, mjv500 commented on tests/dump_dynamical_matrices/Makefile
> +	dump_dynamical_matrices
done

2024-04-02 22:19 UTC, mjv500 commented
> As I understand, the code currently reads in the force constants and dumps to an Abinit DDB file. Would `convert_forceconstant_to_abinit_ddb` be a better name, in line with https://github.com/ollehellman/tdep-devel/tree/master/src/convert_abinit_ddb_to_forceconstant ?

name can stay unchanged - the idea is others beyond abinit may want their own export  options, and the infrastructure is there.

2024-04-03 11:01 UTC, flokno commented on tests/dump_dynamical_matrices/test_dump_dynamical_matrices.py
https://github.com/tdep-developers/tdep/tree/main/tests#run-tests

2024-04-05 09:05 UTC, flokno approved these changes
looks good

2024-04-08 08:03 UTC, flokno commented
Merge @mjv500 ?

2024-04-08 12:41 UTC, merged

2024-04-08 12:42 UTC, mjv500 commented
Thanks for the time and nagging flokno!